import { NormalisedSpec } from '../spec/types';
import { faker } from '@faker-js/faker';

interface PostmanItem {
  name: string;
  request: {
    method: string;
    header: { key: string; value: string }[];
    body?: { mode: string; raw: string; options: { raw: { language: string } } };
    url: { raw: string; host: string[]; path: string[]; variable?: { key: string; value: string }[]; query?: { key: string; value: string }[] };
  };
}

interface PostmanFolder {
  name: string;
  item: PostmanItem[];
}

interface PostmanCollection {
  info: { name: string; schema: string; description: string };
  item: PostmanFolder[];
  variable: { key: string; value: string; type: string }[];
}

const MUTATING = new Set(['post', 'put', 'patch']);

export function buildPostmanCollection(spec: NormalisedSpec, baseUrl: string): PostmanCollection {
  const byTag: Record<string, PostmanItem[]> = {};

  for (const route of spec.routes) {
    const tag = route.tags[0] ?? 'General';
    if (!byTag[tag]) byTag[tag] = [];

    const method = route.method.toUpperCase();
    const pathParts = route.path.split('/').filter(Boolean);

    // Convert Express :param to Postman {{param}}
    const postmanPath = pathParts.map(p => p.startsWith(':') ? `{{${p.slice(1)}}}` : p);
    const rawUrl = `{{baseUrl}}/${postmanPath.join('/')}`;

    // Path variables
    const variables = route.pathParams.map(p => ({
      key: p.name,
      value: `test-${p.name}`,
    }));

    // Query params
    const query = route.queryParams.map(p => ({
      key: p.name,
      value: '',
    }));

    // Request body for mutating methods
    let body;
    if (MUTATING.has(route.method) && route.requestBodySchema) {
      const { generateFromSchema } = require('./handlers/mock');
      let sample: unknown = {};
      try {
        const { generateFromSchema: gen } = require('../faker/generator');
        sample = gen(route.requestBodySchema);
      } catch { sample = {}; }
      body = {
        mode: 'raw',
        raw: JSON.stringify(sample, null, 2),
        options: { raw: { language: 'json' } },
      };
    }

    const item: PostmanItem = {
      name: route.operationId ?? `${method} ${route.path}`,
      request: {
        method,
        header: [
          { key: 'Content-Type', value: 'application/json' },
          { key: 'Authorization', value: 'Bearer {{token}}' },
        ],
        ...(body ? { body } : {}),
        url: {
          raw: rawUrl,
          host: ['{{baseUrl}}'],
          path: postmanPath,
          ...(variables.length ? { variable: variables } : {}),
          ...(query.length ? { query } : {}),
        },
      },
    };

    byTag[tag].push(item);
  }

  const folders: PostmanFolder[] = Object.entries(byTag).map(([name, items]) => ({
    name,
    item: items,
  }));

  return {
    info: {
      name: spec.title,
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
      description: `Auto-generated by mockr from ${spec.title} (v${spec.version})`,
    },
    item: folders,
    variable: [
      { key: 'baseUrl', value: baseUrl, type: 'string' },
      { key: 'token',   value: 'your-token-here', type: 'string' },
    ],
  };
}
