#!/usr/bin/env node
/**
 * mockr MCP Server
 *
 * Exposes mockr capabilities as MCP tools so AI assistants
 * (Claude, Cursor, Copilot, etc.) can:
 *  - Inspect OpenAPI specs
 *  - Generate mock configs
 *  - Query running mock servers
 *  - Add/update overrides on the fly
 *
 * Usage in Claude Desktop (claude_desktop_config.json):
 * {
 *   "mcpServers": {
 *     "mockr": {
 *       "command": "node",
 *       "args": ["/path/to/mockr/dist/mcp.js"]
 *     }
 *   }
 * }
 */

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import fs from 'fs';
import path from 'path';

// Lazy imports to avoid loading spec parser unless needed
async function loadMockrCore() {
  const { loadSpec }    = await import('../spec/loader');
  const { parseSpec }   = await import('../spec/parser');
  const { resolveSpec } = await import('../spec/resolver');
  return { loadSpec, parseSpec, resolveSpec };
}

const server = new McpServer({
  name:    'mockr',
  version: '0.1.2',
});

// ── Tool 1: inspect_spec ─────────────────────────────────────────────────────
server.tool(
  'inspect_spec',
  'Load an OpenAPI spec and return a summary of all routes, tags, and schemas',
  { spec: z.string().describe('Path to local spec file or HTTP/HTTPS URL') },
  async ({ spec: specInput }) => {
    try {
      const { loadSpec, parseSpec, resolveSpec } = await loadMockrCore();
      const raw     = await loadSpec(specInput);
      const parsed  = await parseSpec(raw);
      const resolved = resolveSpec(parsed);

      const summary = {
        title:   resolved.title,
        version: resolved.version,
        total:   resolved.routes.length,
        tags:    [...new Set(resolved.routes.flatMap(r => r.tags))],
        routes:  resolved.routes.map(r => ({
          method:      r.method.toUpperCase(),
          path:        r.path,
          operationId: r.operationId,
          summary:     r.summary,
          tags:        r.tags,
          statusCode:  r.statusCode,
          hasBody:     Object.keys(r.requestBodySchema ?? {}).length > 0,
          hasSchema:   Object.keys(r.responseSchema).length > 0,
        })),
      };

      return {
        content: [{
          type: 'text',
          text: JSON.stringify(summary, null, 2),
        }],
      };
    } catch (err) {
      return { content: [{ type: 'text', text: `Error: ${(err as Error).message}` }], isError: true };
    }
  }
);

// ── Tool 2: generate_mock_config ──────────────────────────────────────────────
server.tool(
  'generate_mock_config',
  'Generate a mockr.json override config from an OpenAPI spec. Returns the config content.',
  {
    spec:    z.string().describe('Path to spec file or URL'),
    filter:  z.string().optional().describe('Filter routes by tag or path substring'),
    outFile: z.string().optional().describe('Write config to this file path (optional)'),
  },
  async ({ spec: specInput, filter, outFile }) => {
    try {
      const { loadSpec, parseSpec, resolveSpec } = await loadMockrCore();
      const { generateFromSchema } = await import('../faker/generator');

      const raw     = await loadSpec(specInput);
      const parsed  = await parseSpec(raw);
      const resolved = resolveSpec(parsed);

      let routes = resolved.routes;
      if (filter) {
        const f = filter.toLowerCase();
        routes = routes.filter(r =>
          r.path.toLowerCase().includes(f) ||
          r.tags.some(t => t.toLowerCase().includes(f)) ||
          (r.operationId ?? '').toLowerCase().includes(f)
        );
      }

      const overrides = routes.map(r => {
        let body: unknown = {};
        try { body = generateFromSchema(r.responseSchema); } catch { body = {}; }
        return {
          method: r.method.toUpperCase(),
          path:   r.path,
          status: r.statusCode,
          body,
        };
      });

      const config = {
        _readme: 'Generated by mockr MCP. Delete entries you don\'t need to override.',
        overrides,
      };

      const json = JSON.stringify(config, null, 2);

      if (outFile) {
        fs.writeFileSync(path.resolve(outFile), json);
        return { content: [{ type: 'text', text: `Written ${overrides.length} overrides to ${outFile}` }] };
      }

      return { content: [{ type: 'text', text: json }] };
    } catch (err) {
      return { content: [{ type: 'text', text: `Error: ${(err as Error).message}` }], isError: true };
    }
  }
);

// ── Tool 3: query_mock_server ─────────────────────────────────────────────────
server.tool(
  'query_mock_server',
  'Query a running mockr server — get routes, health, or make a test request',
  {
    baseUrl: z.string().describe('Base URL of the running mockr server e.g. http://localhost:3001'),
    action:  z.enum(['health', 'routes', 'request']).describe('What to do'),
    method:  z.string().optional().describe('HTTP method for action=request'),
    path:    z.string().optional().describe('Path for action=request e.g. /api/users'),
    body:    z.string().optional().describe('JSON body string for action=request'),
  },
  async ({ baseUrl, action, method, path: reqPath, body }) => {
    try {
      const base = baseUrl.replace(/\/$/, '');

      if (action === 'health') {
        const res  = await fetch(`${base}/__mockr/health`);
        const data = await res.json();
        return { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }] };
      }

      if (action === 'routes') {
        const res    = await fetch(`${base}/__mockr/routes`);
        const routes = await res.json();
        return { content: [{ type: 'text', text: JSON.stringify(routes, null, 2) }] };
      }

      if (action === 'request') {
        if (!reqPath) throw new Error('path is required for action=request');
        const m   = (method ?? 'GET').toUpperCase();
        const url = `${base}${reqPath}`;
        const res = await fetch(url, {
          method: m,
          headers: { 'Content-Type': 'application/json' },
          body: body ? body : undefined,
        });
        const text = await res.text();
        let parsed: unknown;
        try { parsed = JSON.parse(text); } catch { parsed = text; }
        return {
          content: [{
            type: 'text',
            text: JSON.stringify({ status: res.status, body: parsed }, null, 2),
          }],
        };
      }

      return { content: [{ type: 'text', text: 'Unknown action' }], isError: true };
    } catch (err) {
      return { content: [{ type: 'text', text: `Error: ${(err as Error).message}` }], isError: true };
    }
  }
);

// ── Tool 4: add_override ─────────────────────────────────────────────────────
server.tool(
  'add_override',
  'Add or update an override in mockr.json without regenerating the whole file',
  {
    configPath: z.string().optional().describe('Path to mockr.json (default: ./mockr.json)'),
    method:     z.string().describe('HTTP method e.g. GET'),
    path:       z.string().describe('Endpoint path e.g. /api/users'),
    status:     z.number().optional().describe('HTTP status code'),
    body:       z.string().optional().describe('JSON response body as string'),
    delay:      z.number().optional().describe('Response delay in ms'),
  },
  async ({ configPath, method, path: overridePath, status, body, delay }) => {
    const filePath = path.resolve(configPath ?? './mockr.json');

    let config: { overrides: Record<string, unknown>[] } = { overrides: [] };
    if (fs.existsSync(filePath)) {
      try { config = JSON.parse(fs.readFileSync(filePath, 'utf8')); } catch {}
    }

    // Remove existing override for same method+path
    config.overrides = (config.overrides ?? []).filter(
      o => !(o.method === method.toUpperCase() && o.path === overridePath)
    );

    const override: Record<string, unknown> = {
      method: method.toUpperCase(),
      path:   overridePath,
    };
    if (status !== undefined) override.status = status;
    if (body)    { try { override.body = JSON.parse(body); } catch { override.body = body; } }
    if (delay)   override.delay = delay;

    config.overrides.push(override);
    fs.writeFileSync(filePath, JSON.stringify(config, null, 2));

    return {
      content: [{
        type: 'text',
        text: `Added override: ${method.toUpperCase()} ${overridePath} → status=${status ?? 'unchanged'}, body=${body ? 'set' : 'unchanged'}`,
      }],
    };
  }
);

// ── Tool 5: explain_mockr ────────────────────────────────────────────────────
server.tool(
  'explain_mockr',
  'Get help on how to use mockr — commands, config format, and examples',
  {},
  async () => {
    const help = `
# mockr — Zero-config OpenAPI Mock Server

## Commands

### Start a mock server
\`\`\`bash
node dist/cli.js serve <spec> [options]

Options:
  -p, --port <number>       Port (default: 3001)
  --delay <ms>              Global response delay
  --seed <number>           Seed for reproducible data
  --watch                   Auto-reload on spec file change
  --proxy <url>             Proxy target (try real API, fall back to mock)
  --proxy-timeout <ms>      Proxy timeout (default: 3000)
  --no-tui                  Plain logging
\`\`\`

### Generate a config file
\`\`\`bash
node dist/cli.js init <spec> [--force]
\`\`\`

## Built-in endpoints (when server is running)
- GET /__mockr/health       → server status
- GET /__mockr/routes       → all mocked routes as JSON
- GET /__mockr/postman      → download Postman collection
- GET /__mockr/ui/          → Web dashboard (live request log, route explorer)
- GET /__mockr/events       → SSE stream for live updates

## mockr.json — custom overrides
Create mockr.json in your project directory:
\`\`\`json
{
  "overrides": [
    {
      "method": "GET",
      "path": "/api/users",
      "status": 200,
      "body": { "users": [], "total": 0 }
    },
    {
      "method": "POST",
      "path": "/auth/login",
      "status": 401,
      "body": { "error": "invalid_credentials" },
      "delay": 300
    }
  ]
}
\`\`\`

Fields: method*, path*, status, body, delay (ms), headers

## x-mockr-delay spec extension
Add to any OpenAPI operation to set per-route delay:
\`\`\`yaml
/api/slow-endpoint:
  get:
    x-mockr-delay: 2000
    summary: This endpoint takes 2 seconds
\`\`\`

## Stateful CRUD
Routes that follow REST patterns (GET /users, POST /users, GET /users/:id etc.)
automatically persist state in memory — creates/updates/deletes are tracked.

## Proxy fallback
\`\`\`bash
node dist/cli.js serve spec.yaml --proxy https://api.example.com
\`\`\`
Tries the real API first, falls back to mock if it fails.
`.trim();

    return { content: [{ type: 'text', text: help }] };
  }
);

// Start the MCP server
async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch(console.error);
